mixed-port: 7890
redir-port: 7892 # redir port for Linux and macOS
allow-lan: true

# Only applicable when setting allow-lan to true
# "*": bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: "*"

# Rule / Global/ Direct (default is Rule)
mode: Rule

log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
    - 8.8.4.4
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
    - 8.8.4.4
  fallback:
    - https://1.1.1.1/dns-query
    - https://doh.dns.sb/dns-query
    - https://public.dns.iij.jp/dns-query
  fallback-filter:
    geoip: true
    domain:
      - '+.desperadoj.com'
      
proxy-providers:
Proxy:
# shadowsocks
# The supported ciphers(encrypt methods):
#   aes-128-gcm aes-192-gcm aes-256-gcm
#   chacha20-ietf-poly1305 xchacha20-ietf-poly1305
#   aes-128-cfb aes-192-cfb aes-256-cfb
#   aes-128-ctr aes-192-ctr aes-256-ctr
#   rc4-md5 chacha20 chacha20-ietf xchacha20

# socks5
- name: "socks"
  type: socks5
  server: 192.168.100.3
  port: 7893
  # username: username
  # password: password
  # tls: true
  # skip-cert-verify: true
  # udp: true

# http
- name: "http"
  type: http
  server: 192.168.100.3
  port: 7893
  # username: username
  # password: password
  # tls: true # https
  # skip-cert-verify: true

proxy-groups:
Proxy Group:

- name: googleone
  type: select
  proxies:
    - socks
    - http
  
- name: 直连
  type: select
  proxies:
    - DIRECT
rule-providers:  
Rule:
- DOMAIN-SUFFIX,cloud.cupronickel.goog,googleone
- DOMAIN-SUFFIX,googleapis.com,googleone
- DOMAIN-SUFFIX,cloud.cupronickel.goog,googleone
- DOMAIN-SUFFIX,googleapis.com,googleone
- IP-CIDR,136.22.0.0/16,直连
- DOMAIN,oauth2.googleapis.com,googleone
- DOMAIN,www.googleapis.com,googleone
- DOMAIN,people.googleapis.com,googleone
- DOMAIN,subscriptionsmobile-pa.googleapis.com,googleone
- DOMAIN,prod.zinc.cloud.cupronickel.goog,googleone
- DOMAIN,www.google.com,googleone
- DOMAIN,assouth.p.g-tun.com,googleone
- DOMAIN,prod.brass.cloud.cupronickel.goog,googleone
